- name: install mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: starting and enabling mysqld
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setting up root password for mysql
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}
