- name: app-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml
  tags: deployment

- name: nodejs
# ansible.builtin.import_role: 
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs.yaml
  tags: deployment

- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
    
- name: installing mongodb client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: connect to mongodb catalogue
  ansible.builtin.command: mongosh {{ MONGODB_HOST }} --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: Loading master data into mongodb
  ansible.builtin.shell: mongosh --host {{ MONGODB_HOST }} </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yaml
  tags: deployment


